spring.datasource.url=jdbc:postgresql://localhost:5433/paw
spring.datasource.username=paw
spring.datasource.password=paw
spring.datasource.driver-class-name=org.postgresql.Driver

app.baseUrl = http://localhost:8080
rankup.api.cors.allowed-origin-patterns=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080,http://*.it.itba.edu.ar,https://*.it.itba.edu.ar
