spring.datasource.url=jdbc:postgresql://localhost/paw-2025b-14
spring.datasource.username=paw-2025b-14
spring.datasource.password=x5Yq9ghTl
spring.datasource.driver-class-name=org.postgresql.Driver

app.baseUrl = http://localhost:8080