spring.datasource.url=jdbc:postgresql://localhost:5433/paw
spring.datasource.username=paw
spring.datasource.password=z
spring.datasource.driver-class-name=org.postgresql.Driver

app.baseUrl = http://localhost:8080